---
name: export_audit_events
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/294168
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/151278
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/458597
milestone: '17.0'
group: group::import and integrate
type: wip
default_enabled: false
