image: python:3.7

stages:
  - build
  - test  
  - deploy

test:
  script:
    - python -m unittest discover tests -v
    
build:
  script: 
    - python setup.py sdist
    
deploy:
  script:
    - scp dist/*.tar.gz $PROD_SERVER_USER@$PROD_SERVER_HOST:/tmp/
  environment: 
    name: production
