---
name: ci_catalog_create_metadata
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/134148
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/430120
milestone: '16.6'
type: development
group: group::pipeline authoring
default_enabled: true
