---
name: exempt_paid_namespace_members_and_enterprise_users_from_identity_verification
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139101
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434810
milestone: '16.7'
type: development
group: group::anti-abuse
default_enabled: false
