---
name: group_user_saml
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138075
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434464
milestone: '16.7'
type: development
group: group::authentication
default_enabled: false
