---
name: mention_autocomplete_backend_filtering
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131250
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/435106
milestone: '16.7'
type: development
group: group::project management
default_enabled: false
