---
name: simplified_labels
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/140239
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/437859
milestone: '16.8'
type: development
group: group::ux paper cuts
default_enabled: false
