---
name: allow_top_level_group_owners_to_create_service_accounts
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/468806
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/163726
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/482400
milestone: '17.4'
group: group::authentication
type: gitlab_com_derisk
default_enabled: false
