---
name: anthropic_code_gen_aigw_migration
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/477891
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/481933
milestone: '17.4'
group: group::code creation
type: gitlab_com_derisk
default_enabled: false
