---
name: default_branch_protection_defaults
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/408152
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/143796
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17516
milestone: '16.10'
group: group::compliance
type: gitlab_com_derisk
default_enabled: false
