---
name: fork_targets_finder_with_parents
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/378243
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/145230
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/442392
milestone: '16.11'
group: group::source code
type: gitlab_com_derisk
default_enabled: false
