---
name: improve_find_records_for_refresh_service
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/484754
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/166138
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/491589
milestone: '17.4'
group: group::authorization
type: gitlab_com_derisk
default_enabled: false
