---
name: lazy_merge_request_committers
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/441204
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/146297
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/443883
milestone: '16.10'
group: group::code review
type: gitlab_com_derisk
default_enabled: false
