---
name: nested_variable_expansion_in_rules_changes_exists
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/327780
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/166779
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/483115
milestone: '17.5'
group: group::pipeline authoring
type: gitlab_com_derisk
default_enabled: false
