---
name: sync_audit_events_to_new_tables
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/454175
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/158202
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/470481
milestone: '17.3'
group: group::compliance
type: gitlab_com_derisk
default_enabled: false
