---
name: upgrade_pdfjs
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/462822
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/165557
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/491426
milestone: '17.5'
group: group::source code
type: gitlab_com_derisk
default_enabled: false
