---
name: use_lease_for_pat_last_used_update
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/468851
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/158577
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/471276
milestone: '17.2'
group: group::scalability
type: gitlab_com_derisk
default_enabled: false
