---
description: Triggered when the nuget metadata endpoint is called by the client
category: API::NugetPackages
action: cli_metadata
identifiers:
- user
product_group: package_registry
milestone: '14.0'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/164498
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
