---
description: Triggered when automatic creation of incidents on alert is disabled in Incident Management
action: disabled_issue_auto_creation_on_alerts
identifiers:
product_group: respond
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/165305
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
