---
description: TODO
action: download_release_asset_file
indentifiers:
- project
- user
product_group: environments
milestone: 15.6
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/166618
distributions:
- ce
tiers:
- free
- premium
- ultimate
