---
description: TODO
action: push_symbol_package
indentifiers:
- project
- namespace
- user
product_group: package_registry
milestone: 14.1
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/166618
distributions:
- ce
tiers:
- free
- premium
- ultimate
additional_properties:
  label:
    description: Always 'redis_hll_counters.user_packages.user_packages_total_unique_counts_monthly'
  property:
    description: TODO (1 unique values)
