---
description: Triggered when the NuGet Search service is called
action: search_package
identifiers:
- project
- namespace
- user
product_group: package_registry
milestone: '14.0'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/164498
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
