---
description: TODO
action: terraform_state_api_request
indentifiers:
- project
- namespace
- user
product_group: environments
milestone: 15.6
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/166618
distributions:
- ce
tiers:
- free
- premium
- ultimate
additional_properties:
  label:
    description: TODO (1 unique values)
