---
name: controller_static_context
feature_issue_url: https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/3593
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/157628
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/470047
milestone: '17.4'
group: group::scalability
type: beta
default_enabled: false
