---
name: use_sidekiq_dedup_signaling
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/471239
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/159215
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/472741
milestone: '17.3'
group: group::scalability
type: beta
default_enabled: false
