---
name: wiki_content_background_job
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/367628
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/146973
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/452495
milestone: '16.11'
group: group::knowledge
type: beta
default_enabled: true
