---
attr: jira_connect_application_key
clusterwide:
default:
description: ID of the OAuth application used to authenticate with the GitLab for
  Jira Cloud app.
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: false
type: string
