include:
  - component: gitlab.com/gitlab-org/components/danger-review/danger-review@1.2.0
    inputs:
      job_image: "${DEFAULT_CI_IMAGE}"
      # By default DANGER_DANGERFILE_PREFIX is not defined but allows JiHu to
      # use a different prefix.
      # See https://jihulab.com/gitlab-cn/gitlab/-/blob/main-jh/jh/.gitlab-ci.yml
      dangerfile: "${DANGER_DANGERFILE_PREFIX}Dangerfile"
      dry_run: true

danger-review:
  extends:
    - .default-retry
    - .ruby-node-cache
    - .review:rules:danger
  variables:
    BUNDLE_WITH: "danger"
  before_script:
    - source scripts/utils.sh
    - bundle_install_script
    - yarn_install_script
